-- schema_pg.sql — AFC web app, PostgreSQL (Supabase) edition.
--
-- The deployed system uses Supabase managed PostgreSQL in place of the
-- single-file SQLite store in schema.sql.  The LOGICAL model is identical;
-- only the physical types differ, exactly as Appendix G documents:
--
--     INTEGER PRIMARY KEY AUTOINCREMENT  ->  BIGINT GENERATED ... AS IDENTITY
--     INTEGER used as boolean            ->  BOOLEAN
--     TEXT datetime('now')               ->  TIMESTAMPTZ DEFAULT now()
--     REAL epoch seconds                 ->  TIMESTAMPTZ
--     REAL measurement                   ->  DOUBLE PRECISION
--
-- IMPORTANT.  schema.sql is NOT the whole SQLite schema.  db.py adds eight
-- further compression_history columns at startup through its _MIGRATIONS
-- list, and creates idx_history_parent.  All of them are inlined below, so a
-- database created from this file needs no migration pass to match a live
-- SQLite one.  Column set verified against a real initialised database:
-- 23 columns on compression_history, not the 15 in schema.sql.
--
-- Apply in the Supabase SQL Editor, or:
--     psql "$AFC_PG_DSN" -f schema_pg.sql
-- Re-running is harmless; every object uses IF NOT EXISTS.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
-- password_hash: werkzeug.security.generate_password_hash (PBKDF2-SHA256).
--   Plaintext passwords are never stored or logged.  This is ACCOUNT password
--   hashing only.  It is NOT file encryption -- the thesis Delimitations
--   exclude encrypting compressed output.
-- Authentication remains the application's own; Supabase Auth is not used, so
-- this table stays the authority for credentials.
CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             TEXT        NOT NULL UNIQUE,
    email                TEXT        NOT NULL UNIQUE,
    password_hash        TEXT        NOT NULL,
    role                 TEXT        NOT NULL DEFAULT 'user'
                                     CHECK (role IN ('admin', 'user')),
    must_change_password BOOLEAN     NOT NULL DEFAULT FALSE,
    is_active            BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);

-- ---------------------------------------------------------------------------
-- app_meta
-- ---------------------------------------------------------------------------
-- Changes on every destructive database reset.  Signed sessions carry this
-- value so an old numeric user id can never authenticate as a new post-reset
-- account that happens to receive the same id.
CREATE TABLE IF NOT EXISTS app_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- compression_history
-- ---------------------------------------------------------------------------
-- One row per file processed (single, batch, or inside an archive).
-- lossless_verified is TRUE only when a SHA-256 round trip was actually run
-- and matched.  Never set optimistically.
-- batch_id groups rows produced by one queue/archive run (NULL for single
-- files).  parent_history_id makes archive member rows children of their
-- durable AFCPAK summary, so deletion removes the complete logical run.
CREATE TABLE IF NOT EXISTS compression_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL
                                  REFERENCES users (id) ON DELETE CASCADE,
    filename          TEXT        NOT NULL,
    operation         TEXT        NOT NULL DEFAULT 'compress'
                                  CHECK (operation IN ('compress',
                                                       'decompress')),
    original_bytes    BIGINT      NOT NULL,
    compressed_bytes  BIGINT      NOT NULL,
    ratio             DOUBLE PRECISION NOT NULL,
    space_saved_pct   DOUBLE PRECISION NOT NULL,
    engine            TEXT        NOT NULL,
    container_format  TEXT        NOT NULL DEFAULT '',
    lossless_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    duration_ms       DOUBLE PRECISION NOT NULL DEFAULT 0,
    batch_id          TEXT,
    parent_history_id BIGINT      REFERENCES compression_history (id)
                                  ON DELETE CASCADE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Added by db.py _MIGRATIONS on SQLite; part of the base table here.
    gzip_bytes        BIGINT      NOT NULL DEFAULT 0,
    huffman_bytes     BIGINT      NOT NULL DEFAULT 0,
    entropy_bits      DOUBLE PRECISION NOT NULL DEFAULT 0,
    block_share_pct   DOUBLE PRECISION NOT NULL DEFAULT 0,
    preset            TEXT        NOT NULL DEFAULT '',
    -- Both hex SHA-256, '' when not applicable.  The Decompress page proves
    -- integrity by comparing restored bytes against sha256_original.
    sha256_original   TEXT        NOT NULL DEFAULT '',
    sha256_container  TEXT        NOT NULL DEFAULT '',
    detected_type     TEXT        NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_history_user    ON compression_history (user_id);
CREATE INDEX IF NOT EXISTS idx_history_created ON compression_history (created_at);
CREATE INDEX IF NOT EXISTS idx_history_batch   ON compression_history (batch_id);
CREATE INDEX IF NOT EXISTS idx_history_parent  ON compression_history (parent_history_id);

-- ---------------------------------------------------------------------------
-- stored_artifacts
-- ---------------------------------------------------------------------------
-- Only produced compressed AFC/AFCPAK bytes are durable.  User uploads and
-- decompressed originals are intentionally absent from this table and from
-- storage.  storage_key is an opaque server-generated identifier; under
-- Supabase it is the object key within the private 'artifacts' bucket, and
-- the column and its UNIQUE constraint are unchanged from SQLite.
CREATE TABLE IF NOT EXISTS stored_artifacts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id       BIGINT      NOT NULL UNIQUE
                                 REFERENCES compression_history (id)
                                 ON DELETE CASCADE,
    user_id          BIGINT      NOT NULL
                                 REFERENCES users (id) ON DELETE CASCADE,
    storage_key      TEXT        NOT NULL UNIQUE,
    download_name    TEXT        NOT NULL,
    mimetype         TEXT        NOT NULL
                                 DEFAULT 'application/octet-stream',
    byte_size        BIGINT      NOT NULL CHECK (byte_size >= 0),
    sha256           TEXT        NOT NULL,
    integrity_status TEXT        NOT NULL DEFAULT 'verified',
    last_verified_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_artifacts_user_created
    ON stored_artifacts (user_id, created_at);

-- ---------------------------------------------------------------------------
-- audit_log
-- ---------------------------------------------------------------------------
-- Security-relevant events: login, login_failed, logout, password_change,
-- admin_view_users, admin_toggle_active, rate_limited.
-- user_id is NULL when the event has no valid user (e.g. bad username).  The
-- username column is kept as plain text alongside it so the record of an
-- event survives deletion of the account it describes.
CREATE TABLE IF NOT EXISTS audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    username   TEXT,
    event      TEXT        NOT NULL,
    detail     TEXT        NOT NULL DEFAULT '',
    ip_address TEXT        NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_event   ON audit_log (event);

-- ---------------------------------------------------------------------------
-- login_attempts  (fixed-window rate limiting)
-- ---------------------------------------------------------------------------
-- One row per failed attempt; rows older than LOGIN_WINDOW_SECONDS are pruned
-- on each check, so the table stays small without a scheduled job.
-- created_at was REAL unix epoch seconds under SQLite.  Appendix G maps it to
-- TIMESTAMPTZ, which turns the window test from epoch subtraction into an
-- interval comparison:  created_at >= now() - make_interval(secs => $1)
CREATE TABLE IF NOT EXISTS login_attempts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   TEXT        NOT NULL,
    ip_address TEXT        NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attempts_lookup
    ON login_attempts (username, ip_address, created_at);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
-- These six statements do NOT affect the application.  Flask connects as the
-- table owner (or with the service role), and both bypass RLS, so every query
-- in db.py behaves exactly as it does against SQLite.
--
-- What they DO affect is Supabase's auto-generated PostgREST API.  Every table
-- in the public schema is reachable over the internet at
-- https://<project>.supabase.co/rest/v1/<table> by any holder of the anon key,
-- and the anon key is designed to be public -- it ships in client code.  With
-- RLS disabled, that path can read and write these tables directly.
--
-- Enabling RLS with NO policies denies that path outright: a role that does
-- not bypass RLS matches no policy, so it sees no rows and can write none.
-- No policies are written here because this application does not use Supabase
-- Auth; there is no auth.uid() to key a policy on.  Ownership is enforced in
-- db.py, and the database's job is simply to refuse everything that does not
-- arrive through the application.
--
-- This is also what makes the Ethical Consideration's claim -- that access to
-- every stored row is "restricted to its owner or an administrator" -- true at
-- the database rather than only in application code.
--
-- If a browser ever calls Supabase directly with the anon key, THAT is when
-- per-table policies become necessary.  Nothing in the current design does.
ALTER TABLE users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_meta            ENABLE ROW LEVEL SECURITY;
ALTER TABLE compression_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE stored_artifacts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log           ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_attempts      ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- SQLite compatibility shim
-- ---------------------------------------------------------------------------
-- db.py is written once and runs on both engines.  Almost all of its SQL is
-- already common to both -- COUNT(*) FILTER, CURRENT_TIMESTAMP, ON CONFLICT
-- DO NOTHING, RETURNING, TRUE/FALSE, and date(), which PostgreSQL also has.
-- instr() is the one exception: it is SQLite's, and PostgreSQL spells the same
-- thing strpos().  Defining it here keeps analytics_by_extension() a single
-- query instead of two backend-specific ones.
--
-- Verified equivalent: instr('report.final.txt', '.') returns 7 on both.
CREATE OR REPLACE FUNCTION instr(text, text) RETURNS integer
    LANGUAGE sql IMMUTABLE STRICT
    AS $$ SELECT strpos($1, $2) $$;
